version: '3.7'

networks:
  motion2nx-net:
    driver: bridge

services:
# SMPC server local, image & weights  provider server, smpc-server0 and smpc-server1 runs 
# in one container
  smpc-server-local:
    image: iudx/motion2nx:latest
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    volumes:
      - type: volume
        source: smpc-server-local
        target: /usr/share/app/build_debwithrelinfo_gcc/
        volume:
          nocopy: false
      - ./Dataprovider/image_provider/images/:/usr/share/app/Dataprovider/image_provider/images/
      - ./Dataprovider/weights_provider/:/usr/share/app/Dataprovider/weights_provider/
      - ./config_files:/usr/share/app/config_files
    restart: on-failure
    networks: 
      - motion2nx-net
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "100m"
    command: bash -c "cd scripts && ./sharegenerator.sh && ./inference.sh && while (true);  do  sleep 10; done"

volumes:
  smpc-server-local: